name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: action/ceckout@v4
      - name: Use Node.js
        uses: action/setup-node@v4
        with:
          node-version: '18.x'
    - run: npm run ci
    - run: npm run lint || true